// Each image was visually inspected. Local originals stay untouched in image/.
// Villa images were downloaded from Corsica Ranger's official partner page.
const photo = (id, file, category, fr, en, it) => ({
  id,
  file,
  category,
  alt: { fr, en, it },
});

export const photoSources = [
  photo(
    "hero",
    "Resized_20231001_185941.JPG",
    "sunset",
    "Un buggy sur une crête face au soleil couchant et à la baie près de Bonifacio",
    "A buggy on a ridge overlooking the bay near Bonifacio at sunset",
    "Un buggy su un crinale davanti al tramonto e alla baia vicino a Bonifacio",
  ),
  photo(
    "buggy",
    "IMG_2412.HEIC",
    "buggy",
    "Un buggy bleu franchit une piste rocheuse dans le maquis",
    "A blue buggy crosses a rocky trail in the Corsican scrubland",
    "Un buggy blu affronta una pista rocciosa nella macchia corsa",
  ),
  photo(
    "quad",
    "IMG_1534.HEIC",
    "quad",
    "Deux personnes casquées à bord d’un quad bleu",
    "Two riders wearing helmets on a blue quad",
    "Due persone con il casco su un quad blu",
  ),
  photo(
    "sunset",
    "IMG_2588.HEIC",
    "sunset",
    "Un buggy quatre places devant la baie et un coucher de soleil orange",
    "A four-seat buggy overlooking the bay under an orange sunset",
    "Un buggy a quattro posti davanti alla baia e a un tramonto arancione",
  ),
  photo(
    "landscape",
    "IMG_2583.HEIC",
    "landscape",
    "La baie et les collines de l’Extrême-Sud au coucher du soleil",
    "The bay and hills of southern Corsica at sunset",
    "La baia e le colline della Corsica meridionale al tramonto",
  ),
  photo(
    "story",
    "IMG_8714.HEIC",
    "story",
    "Un groupe de visiteurs souriants sur un belvédère au-dessus de la baie",
    "A smiling group of visitors at a viewpoint overlooking the bay",
    "Un gruppo di visitatori sorridenti su un belvedere sopra la baia",
  ),
  photo(
    "bergerie",
    "IMG_0061.HEIC",
    "bergerie",
    "Une chèvre blanche entre les rochers fleuris de la bergerie",
    "A white goat among flower-covered rocks at the sheepfold",
    "Una capra bianca tra le rocce fiorite della bergerie",
  ),
  photo(
    "buggy-clients",
    "IMG_4159.HEIC",
    "buggy",
    "Deux visiteurs souriants dans un buggy bleu sur une piste",
    "Two smiling visitors in a blue buggy on a trail",
    "Due visitatori sorridenti in un buggy blu su una pista",
  ),
  photo(
    "buggy-piste",
    "IMG_1969.JPG",
    "buggy",
    "Un buggy gravit une piste de pierres entre les arbres",
    "A buggy climbs a rocky trail between the trees",
    "Un buggy sale lungo una pista sassosa tra gli alberi",
  ),
  photo(
    "buggy-foret",
    "IMG_0972.JPG",
    "buggy",
    "Un buggy rouge et noir sur une piste au cœur du maquis",
    "A red and black buggy on a trail through the scrubland",
    "Un buggy rosso e nero su una pista nel cuore della macchia",
  ),
  photo(
    "buggy-maquis",
    "IMG_4649.HEIC",
    "buggy",
    "Un buggy bleu arrêté sur les rochers au milieu du maquis",
    "A blue buggy parked on rocks among the scrubland",
    "Un buggy blu fermo sulle rocce nella macchia",
  ),
  photo(
    "buggy-phares",
    "IMG_9873.HEIC",
    "sunset",
    "Un buggy aux phares allumés devant le soleil couchant et la mer",
    "A buggy with its headlights on in front of the sunset and the sea",
    "Un buggy con i fari accesi davanti al tramonto e al mare",
  ),
  photo(
    "buggy-soiree",
    "IMG_2189.HEIC",
    "sunset",
    "Un buggy bleu sur une crête au-dessus de la vallée au couchant",
    "A blue buggy on a ridge above the valley at sunset",
    "Un buggy blu su un crinale sopra la valle al tramonto",
  ),
  photo(
    "convoi-sunset",
    "IMG_3790.HEIC",
    "sunset",
    "Plusieurs buggys alignés au-dessus de la baie sous un ciel de fin de journée",
    "Several buggies lined up above the bay under an evening sky",
    "Diversi buggy allineati sopra la baia sotto il cielo della sera",
  ),
  photo(
    "raids",
    "IMG_8353.HEIC",
    "buggy",
    "Un convoi de buggys sur une piste du maquis en journée",
    "A convoy of buggies on a scrubland trail during the day",
    "Un convoglio di buggy su una pista della macchia durante il giorno",
  ),
  photo(
    "quad-duo",
    "IMG_2227.JPG",
    "quad",
    "Deux personnes casquées sur un quad blanc à l’ombre des arbres",
    "Two riders wearing helmets on a white quad in the shade of trees",
    "Due persone con il casco su un quad bianco all’ombra degli alberi",
  ),
  photo(
    "chevres-rocher",
    "IMG_6183.JPG",
    "bergerie",
    "Deux chèvres sur un rocher devant un mur de pierre",
    "Two goats on a rock in front of a stone wall",
    "Due capre su una roccia davanti a un muro di pietra",
  ),
  photo(
    "bergerie-chevreau",
    "IMG_5846.JPG",
    "bergerie",
    "Un jeune homme porte un chevreau devant la bergerie en bois",
    "A young man holds a kid goat in front of the wooden sheepfold",
    "Un giovane tiene in braccio un capretto davanti alla bergerie in legno",
  ),
  photo(
    "famille-bergerie",
    "IMG_9374.JPG",
    "bergerie",
    "Des enfants et des adultes découvrent les chèvres à la bergerie",
    "Children and adults meet the goats at the sheepfold",
    "Bambini e adulti incontrano le capre alla bergerie",
  ),
  photo(
    "famille-buggy",
    "IMG_7688.HEIC",
    "buggy",
    "Trois visiteurs devant leur buggy bleu au coucher du soleil",
    "Three visitors in front of their blue buggy at sunset",
    "Tre visitatori davanti al loro buggy blu al tramonto",
  ),
  photo(
    "buggy-rouge",
    "IMG_9867.HEIC",
    "sunset",
    "Un buggy rouge et noir sur une crête au-dessus de la baie au soleil couchant",
    "A red and black buggy on a ridge above the bay at sunset",
    "Un buggy rosso e nero su un crinale sopra la baia al tramonto",
  ),
  photo(
    "rocher-bonifacio",
    "IMG_0968.JPG",
    "landscape",
    "Un grand rocher clair au milieu du maquis sous le ciel bleu",
    "A large pale rock among the scrubland under a blue sky",
    "Una grande roccia chiara nella macchia sotto il cielo blu",
  ),
  photo(
    "lavezzi-1",
    "villas-officielles/villa-lavezzi-1.jpg",
    "lavezzi",
    "La piscine privée et le spa de la Villa Lavezzi parmi les pierres et les arbres",
    "Villa Lavezzi’s private pool and spa among stones and trees",
    "La piscina privata e la spa di Villa Lavezzi tra pietre e alberi",
  ),
  photo(
    "lavezzi-2",
    "villas-officielles/villa-lavezzi-2.jpg",
    "lavezzi",
    "La piscine et le spa de la Villa Lavezzi vus depuis la terrasse",
    "Villa Lavezzi’s pool and spa seen from the terrace",
    "La piscina e la spa di Villa Lavezzi viste dalla terrazza",
  ),
  photo(
    "lavezzi-3",
    "villas-officielles/villa-lavezzi-3.jpg",
    "lavezzi",
    "Le séjour lumineux et la table ronde de la Villa Lavezzi",
    "Villa Lavezzi’s bright living room and round dining table",
    "Il soggiorno luminoso e il tavolo rotondo di Villa Lavezzi",
  ),
  photo(
    "lavezzi-4",
    "villas-officielles/villa-lavezzi-4.jpg",
    "lavezzi",
    "Une chambre à deux lits de la Villa Lavezzi avec placard miroir",
    "A twin bedroom at Villa Lavezzi with a mirrored wardrobe",
    "Una camera con due letti di Villa Lavezzi e armadio a specchio",
  ),
  photo(
    "lavezzi-5",
    "villas-officielles/villa-lavezzi-5.jpg",
    "lavezzi",
    "Une chambre double aux tons jaunes à la Villa Lavezzi",
    "A yellow-toned double bedroom at Villa Lavezzi",
    "Una camera matrimoniale dai toni gialli di Villa Lavezzi",
  ),
  photo(
    "lavezzi-6",
    "villas-officielles/villa-lavezzi-6.jpg",
    "lavezzi",
    "Une chambre double aux tons clairs à la Villa Lavezzi",
    "A light-toned double bedroom at Villa Lavezzi",
    "Una camera matrimoniale dai toni chiari di Villa Lavezzi",
  ),
  photo(
    "cavallo-1",
    "villas-officielles/villa-cavallo-1.jpg",
    "cavallo",
    "La façade en pierre et la piscine privée de la Villa Cavallo",
    "Villa Cavallo’s stone façade and private swimming pool",
    "La facciata in pietra e la piscina privata di Villa Cavallo",
  ),
  photo(
    "cavallo-2",
    "villas-officielles/villa-cavallo-2.jpg",
    "cavallo",
    "La Villa Cavallo en pierre et son jardin arboré",
    "The stone-built Villa Cavallo and its leafy garden",
    "Villa Cavallo in pietra e il suo giardino alberato",
  ),
  photo(
    "cavallo-3",
    "villas-officielles/villa-cavallo-3.jpg",
    "cavallo",
    "La salle à manger ouverte sur le séjour de la Villa Cavallo",
    "Villa Cavallo’s dining room opening onto the living room",
    "La sala da pranzo aperta sul soggiorno di Villa Cavallo",
  ),
  photo(
    "cavallo-4",
    "villas-officielles/villa-cavallo-4.jpg",
    "cavallo",
    "Une chambre double au mur rouge à la Villa Cavallo",
    "A double bedroom with a red wall at Villa Cavallo",
    "Una camera matrimoniale con parete rossa di Villa Cavallo",
  ),
  photo(
    "cavallo-5",
    "villas-officielles/villa-cavallo-5.jpg",
    "cavallo",
    "La terrasse couverte de la Villa Cavallo avec vue sur le maquis",
    "Villa Cavallo’s covered terrace overlooking the scrubland",
    "La terrazza coperta di Villa Cavallo con vista sulla macchia",
  ),
  photo(
    "cavallo-6",
    "villas-officielles/villa-cavallo-6.jpg",
    "cavallo",
    "Une chambre double aux tons gris à la Villa Cavallo",
    "A grey-toned double bedroom at Villa Cavallo",
    "Una camera matrimoniale dai toni grigi di Villa Cavallo",
  ),
  photo(
    "convoi-crepuscule",
    "ajouts-2026-10/IMG_9214.jpg",
    "sunset",
    "Un convoi de buggys sur une piste du maquis à la tombée du jour",
    "A convoy of buggies on a scrubland trail at dusk",
    "Un convoglio di buggy su una pista della macchia al crepuscolo",
  ),
  photo(
    "buggy-nuit-lune",
    "ajouts-2026-10/IMG_9219.JPG",
    "buggy",
    "Des buggys sur une piste de nuit éclairée par leurs phares sous la pleine lune",
    "Buggies on a night trail lit by their headlights under a full moon",
    "Buggy su una pista notturna illuminata dai fari sotto la luna piena",
  ),
  photo(
    "piste-nuit",
    "ajouts-2026-10/IMG_9229.JPG",
    "buggy",
    "Des buggys traversent une piste rocheuse entre les arbustes sous la lune",
    "Buggies cross a rocky trail between shrubs under the moon",
    "Buggy percorrono una pista rocciosa tra gli arbusti sotto la luna",
  ),
  photo(
    "convoi-nocturne",
    "ajouts-2026-10/IMG_9232.JPG",
    "buggy",
    "Les feux rouges d’un convoi de buggys sur une piste du maquis la nuit",
    "The red lights of a buggy convoy on a scrubland trail at night",
    "Le luci rosse di un convoglio di buggy su una pista della macchia di notte",
  ),
  photo(
    "chevre-sommet",
    "ajouts-2026-10/IMG_9285.JPG",
    "bergerie",
    "Une chèvre blanche debout au sommet d’un grand rocher de granit",
    "A white goat standing on top of a large granite boulder",
    "Una capra bianca in cima a un grande masso di granito",
  ),
  photo(
    "chevre-maquis",
    "ajouts-2026-10/IMG_9286.JPG",
    "bergerie",
    "Une chèvre blanche sur un rocher entouré d’arbres et de maquis",
    "A white goat on a boulder surrounded by trees and scrubland",
    "Una capra bianca su una roccia circondata da alberi e macchia",
  ),
  photo(
    "convoi-ranger",
    "ajouts-2026-10/IMG_9386.JPG",
    "buggy",
    "Des buggys alignés sur une piste poussiéreuse sous le ciel doré du soir",
    "Buggies lined up on a dusty trail under a golden evening sky",
    "Buggy allineati su una pista polverosa sotto il cielo dorato della sera",
  ),
  photo(
    "ciel-orange",
    "ajouts-2026-10/IMG_9403.JPG",
    "landscape",
    "Un croissant lumineux dans le ciel orangé au-dessus du maquis",
    "A bright crescent in the orange sky above the scrubland",
    "Una mezzaluna luminosa nel cielo arancione sopra la macchia",
  ),
  photo(
    "retour-sunset",
    "ajouts-2026-10/IMG_9409.JPG",
    "sunset",
    "Un convoi de buggys vu de dos sur une piste face au coucher du soleil",
    "A buggy convoy seen from behind on a trail facing the sunset",
    "Un convoglio di buggy visto da dietro su una pista verso il tramonto",
  ),
  photo(
    "ranger-soir",
    "ajouts-2026-10/IMG_9419.JPG",
    "sunset",
    "Des buggys face à l’objectif sur une piste sous un ciel de fin de journée",
    "Buggies facing the camera on a trail under an evening sky",
    "Buggy rivolti verso l’obiettivo su una pista sotto il cielo della sera",
  ),
  photo(
    "piste-doree",
    "ajouts-2026-10/IMG_9435.JPG",
    "sunset",
    "Des buggys suivent une piste du maquis vers le soleil à l’horizon",
    "Buggies follow a scrubland trail towards the sun on the horizon",
    "Buggy seguono una pista nella macchia verso il sole all’orizzonte",
  ),
  photo(
    "ranger-crepuscule",
    "ajouts-2026-10/IMG_9440.JPG",
    "sunset",
    "Un buggy sombre en tête de convoi sous un ciel rose et orange au crépuscule",
    "A dark buggy at the front of a convoy under a pink and orange dusk sky",
    "Un buggy scuro in testa a un convoglio sotto un cielo rosa e arancione al crepuscolo",
  ),
  photo(
    "general-bonifacio",
    "ajouts-2026-10/site-officiel-general-bonifacio.JPG",
    "buggy",
    "Un Polaris General orange et noir avec deux visiteurs devant la mer et les falaises de Bonifacio",
    "An orange and black Polaris General with two visitors overlooking the sea and Bonifacio’s cliffs",
    "Un Polaris General arancione e nero con due visitatori davanti al mare e alle falesie di Bonifacio",
  ),
  photo(
    "quad-coucher-soleil",
    "ajouts-2026-10/site-officiel-quad-coucher-soleil.jpg",
    "quad",
    "Un quad gris avec deux casques devant la baie au coucher du soleil",
    "A grey quad with two helmets overlooking the bay at sunset",
    "Un quad grigio con due caschi davanti alla baia al tramonto",
  ),
  photo(
    "social-convoi-soleil",
    "reseaux-officiels/facebook-convoi-buggys-coucher-soleil.jpg",
    "buggy",
    "Un convoi de buggys entre les rochers et le maquis sous un soleil orange",
    "A buggy convoy among rocks and scrubland under an orange sun",
    "Un convoglio di buggy tra le rocce e la macchia sotto un sole arancione",
  ),
  photo(
    "social-rzr-soleil",
    "reseaux-officiels/instagram-rzr-bleu-coucher-soleil.jpg",
    "buggy",
    "Un buggy Polaris RZR bleu et noir sous un ciel flamboyant au coucher du soleil",
    "A blue and black Polaris RZR buggy under a fiery sunset sky",
    "Un buggy Polaris RZR blu e nero sotto un cielo infuocato al tramonto",
  ),
  photo(
    "social-rzr-phares",
    "reseaux-officiels/instagram-rzr-phares-piste.jpg",
    "buggy",
    "Un buggy aux phares allumés sur une piste rocheuse devant la mer",
    "A buggy with its headlights on along a rocky trail overlooking the sea",
    "Un buggy con i fari accesi su una pista rocciosa davanti al mare",
  ),
  photo(
    "social-buggy-belvedere",
    "reseaux-officiels/facebook-buggy-point-vue.jpg",
    "buggy",
    "Un buggy arrêté sur un belvédère au soleil couchant avec une chèvre au premier plan",
    "A buggy parked at a viewpoint at sunset with a goat in the foreground",
    "Un buggy fermo su un belvedere al tramonto con una capra in primo piano",
  ),
  photo(
    "social-convoi-crepuscule",
    "reseaux-officiels/instagram-convoi-crepuscule.jpg",
    "buggy",
    "Un convoi de buggys sur une piste étroite du maquis face au ciel rose du soir",
    "A buggy convoy on a narrow scrubland trail facing a pink evening sky",
    "Un convoglio di buggy su una stretta pista nella macchia davanti al cielo rosa della sera",
  ),
  photo(
    "social-bergerie-soleil",
    "reseaux-officiels/instagram-bergerie-soleil.jpg",
    "bergerie",
    "La cheminée en pierre de la bergerie dans la lumière dorée du soir",
    "The sheepfold’s stone chimney in the golden evening light",
    "Il camino in pietra della bergerie nella luce dorata della sera",
  ),
  photo(
    "social-panorama-soleil",
    "reseaux-officiels/instagram-panorama-mer-soleil.jpg",
    "landscape",
    "Le soleil orange descend sur la mer au-delà des collines et du maquis",
    "The orange sun sets over the sea beyond the hills and scrubland",
    "Il sole arancione tramonta sul mare oltre le colline e la macchia",
  ),
  photo(
    "social-buggy-bleu-orange",
    "reseaux-officiels/instagram-buggy-bleu-et-orange.jpg",
    "buggy",
    "Un buggy bleu et l’avant d’un buggy orange sous le ciel du soir",
    "A blue buggy beside the front of an orange buggy under an evening sky",
    "Un buggy blu accanto alla parte anteriore di un buggy arancione sotto il cielo della sera",
  ),
  photo(
    "social-quad-rouge",
    "reseaux-officiels/instagram-quad-rouge-depart.jpg",
    "quad",
    "Un quad rouge à deux places à la base de départ de Corsica Ranger",
    "A red two-seat quad at Corsica Ranger’s departure base",
    "Un quad rosso a due posti alla base di partenza di Corsica Ranger",
  ),
  photo(
    "social-general-soleil",
    "reseaux-officiels/instagram-general-orange-soleil.jpg",
    "buggy",
    "Un Polaris General orange et noir sur une piste au coucher du soleil",
    "An orange and black Polaris General on a trail at sunset",
    "Un Polaris General arancione e nero su una pista al tramonto",
  ),
  photo(
    "social-quad-crique",
    "reseaux-officiels/facebook-quad-bord-mer.jpg",
    "quad",
    "Un quad au bord d’une crique rocheuse et de la mer bleue",
    "A quad beside a rocky cove and the blue sea",
    "Un quad accanto a una cala rocciosa e al mare blu",
  ),
  photo(
    "social-base-oliviers",
    "reseaux-officiels/instagram-base-quads-oliviers.jpg",
    "quad",
    "Des quads à la base de départ à l’ombre des oliviers",
    "Quads at the departure base in the shade of olive trees",
    "Quad alla base di partenza all’ombra degli ulivi",
  ),
  photo(
    "social-flotte-quads",
    "reseaux-officiels/instagram-flotte-quads.jpg",
    "quad",
    "Des quads noirs et gris alignés à la base Corsica Ranger",
    "Black and grey quads lined up at the Corsica Ranger base",
    "Quad neri e grigi allineati alla base Corsica Ranger",
  ),
];

// Editorial choices reuse gallery entries, so aliases never duplicate photos.
export const photoAliases = {
  introMain: "convoi-ranger",
  introSmall: "quad-duo",
  buggy: "buggy-maquis",
  quad: "quad-coucher-soleil",
  quadHero: "quad-coucher-soleil",
  story: "general-bonifacio",
};

// Provenance stays with the source list; personal absolute paths are omitted.
const userPhotoProvenance = Object.fromEntries(
  photoSources
    .filter((entry) => entry.file.startsWith("ajouts-2026-10/IMG_"))
    .map((entry) => [
      entry.id,
      { kind: "user", file: entry.file, suppliedOn: "2026-10-07" },
    ]),
);
const socialPublications = {
  "social-convoi-soleil": ["Facebook", "2025-09-08", "https://www.facebook.com/photo/?fbid=1346146490846752&set=a.507620298032713"],
  "social-rzr-soleil": ["Instagram", "2026-09-13", "https://www.instagram.com/corsicaranger/p/DdO_RVgiuNT/"],
  "social-rzr-phares": ["Instagram", "2026-09-13", "https://www.instagram.com/corsicaranger/p/DdO_RVgiuNT/"],
  "social-buggy-belvedere": ["Facebook", "2025-12-17", "https://www.facebook.com/photo/?fbid=1437093161752084&set=pb.100063542414506.-2207520000"],
  "social-convoi-crepuscule": ["Instagram", "2026-08-01", "https://www.instagram.com/corsicaranger/p/Dbfvu5qijOn/"],
  "social-bergerie-soleil": ["Instagram", "2026-07-30", "https://www.instagram.com/corsicaranger/p/DbaoSwQigSJ/"],
  "social-panorama-soleil": ["Instagram", "2026-07-30", "https://www.instagram.com/corsicaranger/p/DbaoSwQigSJ/"],
  "buggy-soiree": ["Facebook", "2025-09-08", "https://www.facebook.com/photo/?fbid=1346143460847055&set=pb.100063542414506.-2207520000"],
  "social-buggy-bleu-orange": ["Instagram", "2026-07-14", "https://www.instagram.com/corsicaranger/p/DaxT29HCnhD/"],
  "social-quad-rouge": ["Instagram", "2026-07-14", "https://www.instagram.com/corsicaranger/p/DaxT29HCnhD/"],
  "social-general-soleil": ["Instagram", "2026-07-02", "https://www.instagram.com/corsicaranger/p/DaTUQeRCni1/"],
  "social-quad-crique": ["Facebook", "2025-09-08", "https://www.facebook.com/photo/?fbid=1346142004180534&set=pb.100063542414506.-2207520000"],
  "social-base-oliviers": ["Instagram", "2026-06-20", "https://www.instagram.com/corsicaranger/p/DZzWQuIiklM/"],
  "social-flotte-quads": ["Instagram", "2026-06-20", "https://www.instagram.com/corsicaranger/p/DZzWQuIiklM/"],
};
export const photoProvenance = {
  ...userPhotoProvenance,
  "general-bonifacio": {
    kind: "official-site",
    file: "ajouts-2026-10/site-officiel-general-bonifacio.JPG",
    sourceUrl: "https://www.corsicaranger.com/images/2016/buggy/IMG_3063.JPG",
    pageUrl: "https://corsicaranger.com/",
    retrievedOn: "2026-10-07",
  },
  "quad-coucher-soleil": {
    kind: "official-site",
    file: "ajouts-2026-10/site-officiel-quad-coucher-soleil.jpg",
    sourceUrl: "https://corsicaranger.com/images/2026/quad/slider/quad-slide-2.jpg",
    pageUrl: "https://corsicaranger.com/location-quad",
    retrievedOn: "2026-10-07",
  },
  ...Object.fromEntries(Object.entries(socialPublications).map(([id, [platform, publishedOn, publicationUrl]]) => [id, {
    kind: "official-social",
    file: photoSources.find((entry) => entry.id === id).file,
    platform,
    publishedOn,
    publicationUrl,
    account: "Corsicaranger",
    retrievedOn: "2026-10-07",
    ...(id === "buggy-soiree" ? { duplicateOfLocalOriginal: true, excludedDuplicateFile: "reseaux-officiels/facebook-rzr-maquis-panorama.jpg" } : {}),
  }])),
};

export const officialVillaBase = "https://corsicaranger.com/images/2024";
export const fontSources = [
  [
    "barlow-condensed-latin.woff2",
    "https://fonts.gstatic.com/s/barlowcondensed/v13/HTxwL3I-JCGChYJ8VI-L6OO_au7B46r2z3bWuYMBYro.woff2",
  ],
  [
    "manrope-latin.woff2",
    "https://fonts.gstatic.com/s/manrope/v20/xn7gYHE41ni1AdIRggexSvfedN4.woff2",
  ],
];
