// Generated by scripts/prepare-assets.mjs. Originals remain in image/.
export const photos = {
  "hero": {
    "id": "hero",
    "src": "/assets/photos/hero-1600.webp",
    "srcset": "/assets/photos/hero-640.webp 640w, /assets/photos/hero-1000.webp 1000w, /assets/photos/hero-1600.webp 1600w, /assets/photos/hero-2000.webp 2000w",
    "width": 1600,
    "height": 721,
    "category": "corse",
    "alt": {
      "fr": "Un buggy sur une crête face au soleil couchant et à la baie près de Bonifacio",
      "en": "A buggy on a ridge overlooking the bay near Bonifacio at sunset",
      "it": "Un buggy su un crinale davanti al tramonto e alla baia vicino a Bonifacio"
    }
  },
  "buggy": {
    "id": "buggy-maquis",
    "src": "/assets/photos/buggy-maquis-1600.webp",
    "srcset": "/assets/photos/buggy-maquis-640.webp 640w, /assets/photos/buggy-maquis-1000.webp 1000w, /assets/photos/buggy-maquis-1600.webp 1600w, /assets/photos/buggy-maquis-2000.webp 2000w",
    "width": 1600,
    "height": 1200,
    "category": "buggy",
    "alt": {
      "fr": "Un buggy bleu arrêté sur les rochers au milieu du maquis",
      "en": "A blue buggy parked on rocks among the scrubland",
      "it": "Un buggy blu fermo sulle rocce nella macchia"
    }
  },
  "quad": {
    "id": "quad-coucher-soleil",
    "src": "/assets/photos/quad-coucher-soleil-1600.webp",
    "srcset": "/assets/photos/quad-coucher-soleil-640.webp 640w, /assets/photos/quad-coucher-soleil-1000.webp 1000w, /assets/photos/quad-coucher-soleil-1600.webp 1600w, /assets/photos/quad-coucher-soleil-2000.webp 2000w",
    "width": 1600,
    "height": 801,
    "category": "quad",
    "alt": {
      "fr": "Un quad gris avec deux casques devant la baie au coucher du soleil",
      "en": "A grey quad with two helmets overlooking the bay at sunset",
      "it": "Un quad grigio con due caschi davanti alla baia al tramonto"
    }
  },
  "sunset": {
    "id": "sunset",
    "src": "/assets/photos/sunset-1600.webp",
    "srcset": "/assets/photos/sunset-640.webp 640w, /assets/photos/sunset-1000.webp 1000w, /assets/photos/sunset-1600.webp 1600w, /assets/photos/sunset-2000.webp 2000w",
    "width": 1600,
    "height": 1200,
    "category": "corse",
    "alt": {
      "fr": "Un buggy quatre places devant la baie et un coucher de soleil orange",
      "en": "A four-seat buggy overlooking the bay under an orange sunset",
      "it": "Un buggy a quattro posti davanti alla baia e a un tramonto arancione"
    }
  },
  "landscape": {
    "id": "landscape",
    "src": "/assets/photos/landscape-1600.webp",
    "srcset": "/assets/photos/landscape-640.webp 640w, /assets/photos/landscape-1000.webp 1000w, /assets/photos/landscape-1600.webp 1600w, /assets/photos/landscape-2000.webp 2000w",
    "width": 1600,
    "height": 1200,
    "category": "corse",
    "alt": {
      "fr": "La baie et les collines de l’Extrême-Sud au coucher du soleil",
      "en": "The bay and hills of southern Corsica at sunset",
      "it": "La baia e le colline della Corsica meridionale al tramonto"
    }
  },
  "story": {
    "id": "general-bonifacio",
    "src": "/assets/photos/general-bonifacio-1600.webp",
    "srcset": "/assets/photos/general-bonifacio-640.webp 640w, /assets/photos/general-bonifacio-1000.webp 1000w, /assets/photos/general-bonifacio-1600.webp 1600w, /assets/photos/general-bonifacio-2000.webp 2000w",
    "width": 1600,
    "height": 1200,
    "category": "buggy",
    "alt": {
      "fr": "Un Polaris General orange et noir avec deux visiteurs devant la mer et les falaises de Bonifacio",
      "en": "An orange and black Polaris General with two visitors overlooking the sea and Bonifacio’s cliffs",
      "it": "Un Polaris General arancione e nero con due visitatori davanti al mare e alle falesie di Bonifacio"
    }
  },
  "bergerie": {
    "id": "bergerie",
    "src": "/assets/photos/bergerie-1600.webp",
    "srcset": "/assets/photos/bergerie-640.webp 640w, /assets/photos/bergerie-1000.webp 1000w, /assets/photos/bergerie-1600.webp 1600w, /assets/photos/bergerie-2000.webp 2000w",
    "width": 1600,
    "height": 1200,
    "category": "corse",
    "alt": {
      "fr": "Une chèvre blanche entre les rochers fleuris de la bergerie",
      "en": "A white goat among flower-covered rocks at the sheepfold",
      "it": "Una capra bianca tra le rocce fiorite della bergerie"
    }
  },
  "lavezzi": {
    "id": "lavezzi-1",
    "src": "/assets/photos/lavezzi-1-1024.webp",
    "srcset": "/assets/photos/lavezzi-1-640.webp 640w, /assets/photos/lavezzi-1-1000.webp 1000w, /assets/photos/lavezzi-1-1024.webp 1024w",
    "width": 1024,
    "height": 768,
    "category": "maisons",
    "alt": {
      "fr": "La piscine privée et le spa de la Villa Lavezzi parmi les pierres et les arbres",
      "en": "Villa Lavezzi’s private pool and spa among stones and trees",
      "it": "La piscina privata e la spa di Villa Lavezzi tra pietre e alberi"
    }
  },
  "cavallo": {
    "id": "cavallo-1",
    "src": "/assets/photos/cavallo-1-953.webp",
    "srcset": "/assets/photos/cavallo-1-640.webp 640w, /assets/photos/cavallo-1-953.webp 953w",
    "width": 953,
    "height": 768,
    "category": "maisons",
    "alt": {
      "fr": "La façade en pierre et la piscine privée de la Villa Cavallo",
      "en": "Villa Cavallo’s stone façade and private swimming pool",
      "it": "La facciata in pietra e la piscina privata di Villa Cavallo"
    }
  },
  "raids": {
    "id": "raids",
    "src": "/assets/photos/raids-1600.webp",
    "srcset": "/assets/photos/raids-640.webp 640w, /assets/photos/raids-1000.webp 1000w, /assets/photos/raids-1600.webp 1600w, /assets/photos/raids-2000.webp 2000w",
    "width": 1600,
    "height": 1200,
    "category": "buggy",
    "alt": {
      "fr": "Un convoi de buggys sur une piste du maquis en journée",
      "en": "A convoy of buggies on a scrubland trail during the day",
      "it": "Un convoglio di buggy su una pista della macchia durante il giorno"
    }
  },
  "introMain": {
    "id": "convoi-ranger",
    "src": "/assets/photos/convoi-ranger-1600.webp",
    "srcset": "/assets/photos/convoi-ranger-640.webp 640w, /assets/photos/convoi-ranger-1000.webp 1000w, /assets/photos/convoi-ranger-1600.webp 1600w, /assets/photos/convoi-ranger-2000.webp 2000w",
    "width": 1600,
    "height": 1200,
    "category": "buggy",
    "alt": {
      "fr": "Des buggys alignés sur une piste poussiéreuse sous le ciel doré du soir",
      "en": "Buggies lined up on a dusty trail under a golden evening sky",
      "it": "Buggy allineati su una pista polverosa sotto il cielo dorato della sera"
    }
  },
  "introSmall": {
    "id": "quad-duo",
    "src": "/assets/photos/quad-duo-1600.webp",
    "srcset": "/assets/photos/quad-duo-640.webp 640w, /assets/photos/quad-duo-1000.webp 1000w, /assets/photos/quad-duo-1600.webp 1600w, /assets/photos/quad-duo-2000.webp 2000w",
    "width": 1600,
    "height": 1200,
    "category": "quad",
    "alt": {
      "fr": "Deux personnes casquées sur un quad blanc à l’ombre des arbres",
      "en": "Two riders wearing helmets on a white quad in the shade of trees",
      "it": "Due persone con il casco su un quad bianco all’ombra degli alberi"
    }
  },
  "quadHero": {
    "id": "quad-coucher-soleil",
    "src": "/assets/photos/quad-coucher-soleil-1600.webp",
    "srcset": "/assets/photos/quad-coucher-soleil-640.webp 640w, /assets/photos/quad-coucher-soleil-1000.webp 1000w, /assets/photos/quad-coucher-soleil-1600.webp 1600w, /assets/photos/quad-coucher-soleil-2000.webp 2000w",
    "width": 1600,
    "height": 801,
    "category": "quad",
    "alt": {
      "fr": "Un quad gris avec deux casques devant la baie au coucher du soleil",
      "en": "A grey quad with two helmets overlooking the bay at sunset",
      "it": "Un quad grigio con due caschi davanti alla baia al tramonto"
    }
  }
};

export const gallery = [
  {
    "id": "hero",
    "src": "/assets/photos/hero-1600.webp",
    "srcset": "/assets/photos/hero-640.webp 640w, /assets/photos/hero-1000.webp 1000w, /assets/photos/hero-1600.webp 1600w, /assets/photos/hero-2000.webp 2000w",
    "width": 1600,
    "height": 721,
    "category": "corse",
    "alt": {
      "fr": "Un buggy sur une crête face au soleil couchant et à la baie près de Bonifacio",
      "en": "A buggy on a ridge overlooking the bay near Bonifacio at sunset",
      "it": "Un buggy su un crinale davanti al tramonto e alla baia vicino a Bonifacio"
    }
  },
  {
    "id": "buggy",
    "src": "/assets/photos/buggy-1600.webp",
    "srcset": "/assets/photos/buggy-640.webp 640w, /assets/photos/buggy-1000.webp 1000w, /assets/photos/buggy-1600.webp 1600w, /assets/photos/buggy-2000.webp 2000w",
    "width": 1600,
    "height": 1200,
    "category": "buggy",
    "alt": {
      "fr": "Un buggy bleu franchit une piste rocheuse dans le maquis",
      "en": "A blue buggy crosses a rocky trail in the Corsican scrubland",
      "it": "Un buggy blu affronta una pista rocciosa nella macchia corsa"
    }
  },
  {
    "id": "quad",
    "src": "/assets/photos/quad-1600.webp",
    "srcset": "/assets/photos/quad-640.webp 640w, /assets/photos/quad-1000.webp 1000w, /assets/photos/quad-1600.webp 1600w, /assets/photos/quad-2000.webp 2000w",
    "width": 1600,
    "height": 1200,
    "category": "quad",
    "alt": {
      "fr": "Deux personnes casquées à bord d’un quad bleu",
      "en": "Two riders wearing helmets on a blue quad",
      "it": "Due persone con il casco su un quad blu"
    }
  },
  {
    "id": "sunset",
    "src": "/assets/photos/sunset-1600.webp",
    "srcset": "/assets/photos/sunset-640.webp 640w, /assets/photos/sunset-1000.webp 1000w, /assets/photos/sunset-1600.webp 1600w, /assets/photos/sunset-2000.webp 2000w",
    "width": 1600,
    "height": 1200,
    "category": "corse",
    "alt": {
      "fr": "Un buggy quatre places devant la baie et un coucher de soleil orange",
      "en": "A four-seat buggy overlooking the bay under an orange sunset",
      "it": "Un buggy a quattro posti davanti alla baia e a un tramonto arancione"
    }
  },
  {
    "id": "landscape",
    "src": "/assets/photos/landscape-1600.webp",
    "srcset": "/assets/photos/landscape-640.webp 640w, /assets/photos/landscape-1000.webp 1000w, /assets/photos/landscape-1600.webp 1600w, /assets/photos/landscape-2000.webp 2000w",
    "width": 1600,
    "height": 1200,
    "category": "corse",
    "alt": {
      "fr": "La baie et les collines de l’Extrême-Sud au coucher du soleil",
      "en": "The bay and hills of southern Corsica at sunset",
      "it": "La baia e le colline della Corsica meridionale al tramonto"
    }
  },
  {
    "id": "story",
    "src": "/assets/photos/story-1600.webp",
    "srcset": "/assets/photos/story-640.webp 640w, /assets/photos/story-1000.webp 1000w, /assets/photos/story-1600.webp 1600w, /assets/photos/story-2000.webp 2000w",
    "width": 1600,
    "height": 1200,
    "category": "buggy",
    "alt": {
      "fr": "Un groupe de visiteurs souriants sur un belvédère au-dessus de la baie",
      "en": "A smiling group of visitors at a viewpoint overlooking the bay",
      "it": "Un gruppo di visitatori sorridenti su un belvedere sopra la baia"
    }
  },
  {
    "id": "bergerie",
    "src": "/assets/photos/bergerie-1600.webp",
    "srcset": "/assets/photos/bergerie-640.webp 640w, /assets/photos/bergerie-1000.webp 1000w, /assets/photos/bergerie-1600.webp 1600w, /assets/photos/bergerie-2000.webp 2000w",
    "width": 1600,
    "height": 1200,
    "category": "corse",
    "alt": {
      "fr": "Une chèvre blanche entre les rochers fleuris de la bergerie",
      "en": "A white goat among flower-covered rocks at the sheepfold",
      "it": "Una capra bianca tra le rocce fiorite della bergerie"
    }
  },
  {
    "id": "buggy-clients",
    "src": "/assets/photos/buggy-clients-1600.webp",
    "srcset": "/assets/photos/buggy-clients-640.webp 640w, /assets/photos/buggy-clients-1000.webp 1000w, /assets/photos/buggy-clients-1600.webp 1600w, /assets/photos/buggy-clients-2000.webp 2000w",
    "width": 1600,
    "height": 1200,
    "category": "buggy",
    "alt": {
      "fr": "Deux visiteurs souriants dans un buggy bleu sur une piste",
      "en": "Two smiling visitors in a blue buggy on a trail",
      "it": "Due visitatori sorridenti in un buggy blu su una pista"
    }
  },
  {
    "id": "buggy-piste",
    "src": "/assets/photos/buggy-piste-1600.webp",
    "srcset": "/assets/photos/buggy-piste-640.webp 640w, /assets/photos/buggy-piste-1000.webp 1000w, /assets/photos/buggy-piste-1600.webp 1600w, /assets/photos/buggy-piste-2000.webp 2000w",
    "width": 1600,
    "height": 1200,
    "category": "buggy",
    "alt": {
      "fr": "Un buggy gravit une piste de pierres entre les arbres",
      "en": "A buggy climbs a rocky trail between the trees",
      "it": "Un buggy sale lungo una pista sassosa tra gli alberi"
    }
  },
  {
    "id": "buggy-foret",
    "src": "/assets/photos/buggy-foret-1600.webp",
    "srcset": "/assets/photos/buggy-foret-640.webp 640w, /assets/photos/buggy-foret-1000.webp 1000w, /assets/photos/buggy-foret-1600.webp 1600w, /assets/photos/buggy-foret-2000.webp 2000w",
    "width": 1600,
    "height": 1200,
    "category": "buggy",
    "alt": {
      "fr": "Un buggy rouge et noir sur une piste au cœur du maquis",
      "en": "A red and black buggy on a trail through the scrubland",
      "it": "Un buggy rosso e nero su una pista nel cuore della macchia"
    }
  },
  {
    "id": "buggy-maquis",
    "src": "/assets/photos/buggy-maquis-1600.webp",
    "srcset": "/assets/photos/buggy-maquis-640.webp 640w, /assets/photos/buggy-maquis-1000.webp 1000w, /assets/photos/buggy-maquis-1600.webp 1600w, /assets/photos/buggy-maquis-2000.webp 2000w",
    "width": 1600,
    "height": 1200,
    "category": "buggy",
    "alt": {
      "fr": "Un buggy bleu arrêté sur les rochers au milieu du maquis",
      "en": "A blue buggy parked on rocks among the scrubland",
      "it": "Un buggy blu fermo sulle rocce nella macchia"
    }
  },
  {
    "id": "buggy-phares",
    "src": "/assets/photos/buggy-phares-1600.webp",
    "srcset": "/assets/photos/buggy-phares-640.webp 640w, /assets/photos/buggy-phares-1000.webp 1000w, /assets/photos/buggy-phares-1600.webp 1600w, /assets/photos/buggy-phares-2000.webp 2000w",
    "width": 1600,
    "height": 1200,
    "category": "corse",
    "alt": {
      "fr": "Un buggy aux phares allumés devant le soleil couchant et la mer",
      "en": "A buggy with its headlights on in front of the sunset and the sea",
      "it": "Un buggy con i fari accesi davanti al tramonto e al mare"
    }
  },
  {
    "id": "buggy-soiree",
    "src": "/assets/photos/buggy-soiree-1600.webp",
    "srcset": "/assets/photos/buggy-soiree-640.webp 640w, /assets/photos/buggy-soiree-1000.webp 1000w, /assets/photos/buggy-soiree-1600.webp 1600w, /assets/photos/buggy-soiree-2000.webp 2000w",
    "width": 1600,
    "height": 1200,
    "category": "corse",
    "alt": {
      "fr": "Un buggy bleu sur une crête au-dessus de la vallée au couchant",
      "en": "A blue buggy on a ridge above the valley at sunset",
      "it": "Un buggy blu su un crinale sopra la valle al tramonto"
    }
  },
  {
    "id": "convoi-sunset",
    "src": "/assets/photos/convoi-sunset-1600.webp",
    "srcset": "/assets/photos/convoi-sunset-640.webp 640w, /assets/photos/convoi-sunset-1000.webp 1000w, /assets/photos/convoi-sunset-1600.webp 1600w, /assets/photos/convoi-sunset-2000.webp 2000w",
    "width": 1600,
    "height": 1200,
    "category": "corse",
    "alt": {
      "fr": "Plusieurs buggys alignés au-dessus de la baie sous un ciel de fin de journée",
      "en": "Several buggies lined up above the bay under an evening sky",
      "it": "Diversi buggy allineati sopra la baia sotto il cielo della sera"
    }
  },
  {
    "id": "raids",
    "src": "/assets/photos/raids-1600.webp",
    "srcset": "/assets/photos/raids-640.webp 640w, /assets/photos/raids-1000.webp 1000w, /assets/photos/raids-1600.webp 1600w, /assets/photos/raids-2000.webp 2000w",
    "width": 1600,
    "height": 1200,
    "category": "buggy",
    "alt": {
      "fr": "Un convoi de buggys sur une piste du maquis en journée",
      "en": "A convoy of buggies on a scrubland trail during the day",
      "it": "Un convoglio di buggy su una pista della macchia durante il giorno"
    }
  },
  {
    "id": "quad-duo",
    "src": "/assets/photos/quad-duo-1600.webp",
    "srcset": "/assets/photos/quad-duo-640.webp 640w, /assets/photos/quad-duo-1000.webp 1000w, /assets/photos/quad-duo-1600.webp 1600w, /assets/photos/quad-duo-2000.webp 2000w",
    "width": 1600,
    "height": 1200,
    "category": "quad",
    "alt": {
      "fr": "Deux personnes casquées sur un quad blanc à l’ombre des arbres",
      "en": "Two riders wearing helmets on a white quad in the shade of trees",
      "it": "Due persone con il casco su un quad bianco all’ombra degli alberi"
    }
  },
  {
    "id": "chevres-rocher",
    "src": "/assets/photos/chevres-rocher-1600.webp",
    "srcset": "/assets/photos/chevres-rocher-640.webp 640w, /assets/photos/chevres-rocher-1000.webp 1000w, /assets/photos/chevres-rocher-1600.webp 1600w, /assets/photos/chevres-rocher-2000.webp 2000w",
    "width": 1600,
    "height": 2133,
    "category": "corse",
    "alt": {
      "fr": "Deux chèvres sur un rocher devant un mur de pierre",
      "en": "Two goats on a rock in front of a stone wall",
      "it": "Due capre su una roccia davanti a un muro di pietra"
    }
  },
  {
    "id": "bergerie-chevreau",
    "src": "/assets/photos/bergerie-chevreau-1600.webp",
    "srcset": "/assets/photos/bergerie-chevreau-640.webp 640w, /assets/photos/bergerie-chevreau-1000.webp 1000w, /assets/photos/bergerie-chevreau-1600.webp 1600w, /assets/photos/bergerie-chevreau-2000.webp 2000w",
    "width": 1600,
    "height": 2133,
    "category": "corse",
    "alt": {
      "fr": "Un jeune homme porte un chevreau devant la bergerie en bois",
      "en": "A young man holds a kid goat in front of the wooden sheepfold",
      "it": "Un giovane tiene in braccio un capretto davanti alla bergerie in legno"
    }
  },
  {
    "id": "famille-bergerie",
    "src": "/assets/photos/famille-bergerie-1600.webp",
    "srcset": "/assets/photos/famille-bergerie-640.webp 640w, /assets/photos/famille-bergerie-1000.webp 1000w, /assets/photos/famille-bergerie-1600.webp 1600w, /assets/photos/famille-bergerie-2000.webp 2000w",
    "width": 1600,
    "height": 2133,
    "category": "corse",
    "alt": {
      "fr": "Des enfants et des adultes découvrent les chèvres à la bergerie",
      "en": "Children and adults meet the goats at the sheepfold",
      "it": "Bambini e adulti incontrano le capre alla bergerie"
    }
  },
  {
    "id": "famille-buggy",
    "src": "/assets/photos/famille-buggy-1600.webp",
    "srcset": "/assets/photos/famille-buggy-640.webp 640w, /assets/photos/famille-buggy-1000.webp 1000w, /assets/photos/famille-buggy-1600.webp 1600w, /assets/photos/famille-buggy-2000.webp 2000w",
    "width": 1600,
    "height": 1200,
    "category": "buggy",
    "alt": {
      "fr": "Trois visiteurs devant leur buggy bleu au coucher du soleil",
      "en": "Three visitors in front of their blue buggy at sunset",
      "it": "Tre visitatori davanti al loro buggy blu al tramonto"
    }
  },
  {
    "id": "buggy-rouge",
    "src": "/assets/photos/buggy-rouge-1600.webp",
    "srcset": "/assets/photos/buggy-rouge-640.webp 640w, /assets/photos/buggy-rouge-1000.webp 1000w, /assets/photos/buggy-rouge-1600.webp 1600w, /assets/photos/buggy-rouge-2000.webp 2000w",
    "width": 1600,
    "height": 1200,
    "category": "corse",
    "alt": {
      "fr": "Un buggy rouge et noir sur une crête au-dessus de la baie au soleil couchant",
      "en": "A red and black buggy on a ridge above the bay at sunset",
      "it": "Un buggy rosso e nero su un crinale sopra la baia al tramonto"
    }
  },
  {
    "id": "rocher-bonifacio",
    "src": "/assets/photos/rocher-bonifacio-1055.webp",
    "srcset": "/assets/photos/rocher-bonifacio-640.webp 640w, /assets/photos/rocher-bonifacio-1000.webp 1000w, /assets/photos/rocher-bonifacio-1055.webp 1055w",
    "width": 1055,
    "height": 1080,
    "category": "corse",
    "alt": {
      "fr": "Un grand rocher clair au milieu du maquis sous le ciel bleu",
      "en": "A large pale rock among the scrubland under a blue sky",
      "it": "Una grande roccia chiara nella macchia sotto il cielo blu"
    }
  },
  {
    "id": "lavezzi-1",
    "src": "/assets/photos/lavezzi-1-1024.webp",
    "srcset": "/assets/photos/lavezzi-1-640.webp 640w, /assets/photos/lavezzi-1-1000.webp 1000w, /assets/photos/lavezzi-1-1024.webp 1024w",
    "width": 1024,
    "height": 768,
    "category": "maisons",
    "alt": {
      "fr": "La piscine privée et le spa de la Villa Lavezzi parmi les pierres et les arbres",
      "en": "Villa Lavezzi’s private pool and spa among stones and trees",
      "it": "La piscina privata e la spa di Villa Lavezzi tra pietre e alberi"
    }
  },
  {
    "id": "lavezzi-2",
    "src": "/assets/photos/lavezzi-2-1024.webp",
    "srcset": "/assets/photos/lavezzi-2-640.webp 640w, /assets/photos/lavezzi-2-1000.webp 1000w, /assets/photos/lavezzi-2-1024.webp 1024w",
    "width": 1024,
    "height": 768,
    "category": "maisons",
    "alt": {
      "fr": "La piscine et le spa de la Villa Lavezzi vus depuis la terrasse",
      "en": "Villa Lavezzi’s pool and spa seen from the terrace",
      "it": "La piscina e la spa di Villa Lavezzi viste dalla terrazza"
    }
  },
  {
    "id": "lavezzi-3",
    "src": "/assets/photos/lavezzi-3-1024.webp",
    "srcset": "/assets/photos/lavezzi-3-640.webp 640w, /assets/photos/lavezzi-3-1000.webp 1000w, /assets/photos/lavezzi-3-1024.webp 1024w",
    "width": 1024,
    "height": 768,
    "category": "maisons",
    "alt": {
      "fr": "Le séjour lumineux et la table ronde de la Villa Lavezzi",
      "en": "Villa Lavezzi’s bright living room and round dining table",
      "it": "Il soggiorno luminoso e il tavolo rotondo di Villa Lavezzi"
    }
  },
  {
    "id": "lavezzi-4",
    "src": "/assets/photos/lavezzi-4-1024.webp",
    "srcset": "/assets/photos/lavezzi-4-640.webp 640w, /assets/photos/lavezzi-4-1000.webp 1000w, /assets/photos/lavezzi-4-1024.webp 1024w",
    "width": 1024,
    "height": 768,
    "category": "maisons",
    "alt": {
      "fr": "Une chambre à deux lits de la Villa Lavezzi avec placard miroir",
      "en": "A twin bedroom at Villa Lavezzi with a mirrored wardrobe",
      "it": "Una camera con due letti di Villa Lavezzi e armadio a specchio"
    }
  },
  {
    "id": "lavezzi-5",
    "src": "/assets/photos/lavezzi-5-1024.webp",
    "srcset": "/assets/photos/lavezzi-5-640.webp 640w, /assets/photos/lavezzi-5-1000.webp 1000w, /assets/photos/lavezzi-5-1024.webp 1024w",
    "width": 1024,
    "height": 768,
    "category": "maisons",
    "alt": {
      "fr": "Une chambre double aux tons jaunes à la Villa Lavezzi",
      "en": "A yellow-toned double bedroom at Villa Lavezzi",
      "it": "Una camera matrimoniale dai toni gialli di Villa Lavezzi"
    }
  },
  {
    "id": "lavezzi-6",
    "src": "/assets/photos/lavezzi-6-1024.webp",
    "srcset": "/assets/photos/lavezzi-6-640.webp 640w, /assets/photos/lavezzi-6-1000.webp 1000w, /assets/photos/lavezzi-6-1024.webp 1024w",
    "width": 1024,
    "height": 768,
    "category": "maisons",
    "alt": {
      "fr": "Une chambre double aux tons clairs à la Villa Lavezzi",
      "en": "A light-toned double bedroom at Villa Lavezzi",
      "it": "Una camera matrimoniale dai toni chiari di Villa Lavezzi"
    }
  },
  {
    "id": "cavallo-1",
    "src": "/assets/photos/cavallo-1-953.webp",
    "srcset": "/assets/photos/cavallo-1-640.webp 640w, /assets/photos/cavallo-1-953.webp 953w",
    "width": 953,
    "height": 768,
    "category": "maisons",
    "alt": {
      "fr": "La façade en pierre et la piscine privée de la Villa Cavallo",
      "en": "Villa Cavallo’s stone façade and private swimming pool",
      "it": "La facciata in pietra e la piscina privata di Villa Cavallo"
    }
  },
  {
    "id": "cavallo-2",
    "src": "/assets/photos/cavallo-2-1024.webp",
    "srcset": "/assets/photos/cavallo-2-640.webp 640w, /assets/photos/cavallo-2-1000.webp 1000w, /assets/photos/cavallo-2-1024.webp 1024w",
    "width": 1024,
    "height": 768,
    "category": "maisons",
    "alt": {
      "fr": "La Villa Cavallo en pierre et son jardin arboré",
      "en": "The stone-built Villa Cavallo and its leafy garden",
      "it": "Villa Cavallo in pietra e il suo giardino alberato"
    }
  },
  {
    "id": "cavallo-3",
    "src": "/assets/photos/cavallo-3-1024.webp",
    "srcset": "/assets/photos/cavallo-3-640.webp 640w, /assets/photos/cavallo-3-1000.webp 1000w, /assets/photos/cavallo-3-1024.webp 1024w",
    "width": 1024,
    "height": 769,
    "category": "maisons",
    "alt": {
      "fr": "La salle à manger ouverte sur le séjour de la Villa Cavallo",
      "en": "Villa Cavallo’s dining room opening onto the living room",
      "it": "La sala da pranzo aperta sul soggiorno di Villa Cavallo"
    }
  },
  {
    "id": "cavallo-4",
    "src": "/assets/photos/cavallo-4-1024.webp",
    "srcset": "/assets/photos/cavallo-4-640.webp 640w, /assets/photos/cavallo-4-1000.webp 1000w, /assets/photos/cavallo-4-1024.webp 1024w",
    "width": 1024,
    "height": 768,
    "category": "maisons",
    "alt": {
      "fr": "Une chambre double au mur rouge à la Villa Cavallo",
      "en": "A double bedroom with a red wall at Villa Cavallo",
      "it": "Una camera matrimoniale con parete rossa di Villa Cavallo"
    }
  },
  {
    "id": "cavallo-5",
    "src": "/assets/photos/cavallo-5-1024.webp",
    "srcset": "/assets/photos/cavallo-5-640.webp 640w, /assets/photos/cavallo-5-1000.webp 1000w, /assets/photos/cavallo-5-1024.webp 1024w",
    "width": 1024,
    "height": 768,
    "category": "maisons",
    "alt": {
      "fr": "La terrasse couverte de la Villa Cavallo avec vue sur le maquis",
      "en": "Villa Cavallo’s covered terrace overlooking the scrubland",
      "it": "La terrazza coperta di Villa Cavallo con vista sulla macchia"
    }
  },
  {
    "id": "cavallo-6",
    "src": "/assets/photos/cavallo-6-1024.webp",
    "srcset": "/assets/photos/cavallo-6-640.webp 640w, /assets/photos/cavallo-6-1000.webp 1000w, /assets/photos/cavallo-6-1024.webp 1024w",
    "width": 1024,
    "height": 768,
    "category": "maisons",
    "alt": {
      "fr": "Une chambre double aux tons gris à la Villa Cavallo",
      "en": "A grey-toned double bedroom at Villa Cavallo",
      "it": "Una camera matrimoniale dai toni grigi di Villa Cavallo"
    }
  },
  {
    "id": "convoi-crepuscule",
    "src": "/assets/photos/convoi-crepuscule-1600.webp",
    "srcset": "/assets/photos/convoi-crepuscule-640.webp 640w, /assets/photos/convoi-crepuscule-1000.webp 1000w, /assets/photos/convoi-crepuscule-1600.webp 1600w, /assets/photos/convoi-crepuscule-2000.webp 2000w",
    "width": 1600,
    "height": 900,
    "category": "corse",
    "alt": {
      "fr": "Un convoi de buggys sur une piste du maquis à la tombée du jour",
      "en": "A convoy of buggies on a scrubland trail at dusk",
      "it": "Un convoglio di buggy su una pista della macchia al crepuscolo"
    }
  },
  {
    "id": "buggy-nuit-lune",
    "src": "/assets/photos/buggy-nuit-lune-1600.webp",
    "srcset": "/assets/photos/buggy-nuit-lune-640.webp 640w, /assets/photos/buggy-nuit-lune-1000.webp 1000w, /assets/photos/buggy-nuit-lune-1600.webp 1600w, /assets/photos/buggy-nuit-lune-2000.webp 2000w",
    "width": 1600,
    "height": 2133,
    "category": "buggy",
    "alt": {
      "fr": "Des buggys sur une piste de nuit éclairée par leurs phares sous la pleine lune",
      "en": "Buggies on a night trail lit by their headlights under a full moon",
      "it": "Buggy su una pista notturna illuminata dai fari sotto la luna piena"
    }
  },
  {
    "id": "piste-nuit",
    "src": "/assets/photos/piste-nuit-1600.webp",
    "srcset": "/assets/photos/piste-nuit-640.webp 640w, /assets/photos/piste-nuit-1000.webp 1000w, /assets/photos/piste-nuit-1600.webp 1600w, /assets/photos/piste-nuit-2000.webp 2000w",
    "width": 1600,
    "height": 2133,
    "category": "buggy",
    "alt": {
      "fr": "Des buggys traversent une piste rocheuse entre les arbustes sous la lune",
      "en": "Buggies cross a rocky trail between shrubs under the moon",
      "it": "Buggy percorrono una pista rocciosa tra gli arbusti sotto la luna"
    }
  },
  {
    "id": "convoi-nocturne",
    "src": "/assets/photos/convoi-nocturne-1600.webp",
    "srcset": "/assets/photos/convoi-nocturne-640.webp 640w, /assets/photos/convoi-nocturne-1000.webp 1000w, /assets/photos/convoi-nocturne-1600.webp 1600w, /assets/photos/convoi-nocturne-2000.webp 2000w",
    "width": 1600,
    "height": 2133,
    "category": "buggy",
    "alt": {
      "fr": "Les feux rouges d’un convoi de buggys sur une piste du maquis la nuit",
      "en": "The red lights of a buggy convoy on a scrubland trail at night",
      "it": "Le luci rosse di un convoglio di buggy su una pista della macchia di notte"
    }
  },
  {
    "id": "chevre-sommet",
    "src": "/assets/photos/chevre-sommet-1600.webp",
    "srcset": "/assets/photos/chevre-sommet-640.webp 640w, /assets/photos/chevre-sommet-1000.webp 1000w, /assets/photos/chevre-sommet-1600.webp 1600w, /assets/photos/chevre-sommet-2000.webp 2000w",
    "width": 1600,
    "height": 2133,
    "category": "corse",
    "alt": {
      "fr": "Une chèvre blanche debout au sommet d’un grand rocher de granit",
      "en": "A white goat standing on top of a large granite boulder",
      "it": "Una capra bianca in cima a un grande masso di granito"
    }
  },
  {
    "id": "chevre-maquis",
    "src": "/assets/photos/chevre-maquis-1600.webp",
    "srcset": "/assets/photos/chevre-maquis-640.webp 640w, /assets/photos/chevre-maquis-1000.webp 1000w, /assets/photos/chevre-maquis-1600.webp 1600w, /assets/photos/chevre-maquis-2000.webp 2000w",
    "width": 1600,
    "height": 2133,
    "category": "corse",
    "alt": {
      "fr": "Une chèvre blanche sur un rocher entouré d’arbres et de maquis",
      "en": "A white goat on a boulder surrounded by trees and scrubland",
      "it": "Una capra bianca su una roccia circondata da alberi e macchia"
    }
  },
  {
    "id": "convoi-ranger",
    "src": "/assets/photos/convoi-ranger-1600.webp",
    "srcset": "/assets/photos/convoi-ranger-640.webp 640w, /assets/photos/convoi-ranger-1000.webp 1000w, /assets/photos/convoi-ranger-1600.webp 1600w, /assets/photos/convoi-ranger-2000.webp 2000w",
    "width": 1600,
    "height": 1200,
    "category": "buggy",
    "alt": {
      "fr": "Des buggys alignés sur une piste poussiéreuse sous le ciel doré du soir",
      "en": "Buggies lined up on a dusty trail under a golden evening sky",
      "it": "Buggy allineati su una pista polverosa sotto il cielo dorato della sera"
    }
  },
  {
    "id": "ciel-orange",
    "src": "/assets/photos/ciel-orange-1600.webp",
    "srcset": "/assets/photos/ciel-orange-640.webp 640w, /assets/photos/ciel-orange-1000.webp 1000w, /assets/photos/ciel-orange-1600.webp 1600w, /assets/photos/ciel-orange-2000.webp 2000w",
    "width": 1600,
    "height": 2133,
    "category": "corse",
    "alt": {
      "fr": "Un croissant lumineux dans le ciel orangé au-dessus du maquis",
      "en": "A bright crescent in the orange sky above the scrubland",
      "it": "Una mezzaluna luminosa nel cielo arancione sopra la macchia"
    }
  },
  {
    "id": "retour-sunset",
    "src": "/assets/photos/retour-sunset-1600.webp",
    "srcset": "/assets/photos/retour-sunset-640.webp 640w, /assets/photos/retour-sunset-1000.webp 1000w, /assets/photos/retour-sunset-1600.webp 1600w, /assets/photos/retour-sunset-2000.webp 2000w",
    "width": 1600,
    "height": 2133,
    "category": "corse",
    "alt": {
      "fr": "Un convoi de buggys vu de dos sur une piste face au coucher du soleil",
      "en": "A buggy convoy seen from behind on a trail facing the sunset",
      "it": "Un convoglio di buggy visto da dietro su una pista verso il tramonto"
    }
  },
  {
    "id": "ranger-soir",
    "src": "/assets/photos/ranger-soir-1600.webp",
    "srcset": "/assets/photos/ranger-soir-640.webp 640w, /assets/photos/ranger-soir-1000.webp 1000w, /assets/photos/ranger-soir-1600.webp 1600w, /assets/photos/ranger-soir-2000.webp 2000w",
    "width": 1600,
    "height": 2133,
    "category": "corse",
    "alt": {
      "fr": "Des buggys face à l’objectif sur une piste sous un ciel de fin de journée",
      "en": "Buggies facing the camera on a trail under an evening sky",
      "it": "Buggy rivolti verso l’obiettivo su una pista sotto il cielo della sera"
    }
  },
  {
    "id": "piste-doree",
    "src": "/assets/photos/piste-doree-1600.webp",
    "srcset": "/assets/photos/piste-doree-640.webp 640w, /assets/photos/piste-doree-1000.webp 1000w, /assets/photos/piste-doree-1600.webp 1600w, /assets/photos/piste-doree-2000.webp 2000w",
    "width": 1600,
    "height": 2133,
    "category": "corse",
    "alt": {
      "fr": "Des buggys suivent une piste du maquis vers le soleil à l’horizon",
      "en": "Buggies follow a scrubland trail towards the sun on the horizon",
      "it": "Buggy seguono una pista nella macchia verso il sole all’orizzonte"
    }
  },
  {
    "id": "ranger-crepuscule",
    "src": "/assets/photos/ranger-crepuscule-1600.webp",
    "srcset": "/assets/photos/ranger-crepuscule-640.webp 640w, /assets/photos/ranger-crepuscule-1000.webp 1000w, /assets/photos/ranger-crepuscule-1600.webp 1600w, /assets/photos/ranger-crepuscule-2000.webp 2000w",
    "width": 1600,
    "height": 2133,
    "category": "corse",
    "alt": {
      "fr": "Un buggy sombre en tête de convoi sous un ciel rose et orange au crépuscule",
      "en": "A dark buggy at the front of a convoy under a pink and orange dusk sky",
      "it": "Un buggy scuro in testa a un convoglio sotto un cielo rosa e arancione al crepuscolo"
    }
  },
  {
    "id": "general-bonifacio",
    "src": "/assets/photos/general-bonifacio-1600.webp",
    "srcset": "/assets/photos/general-bonifacio-640.webp 640w, /assets/photos/general-bonifacio-1000.webp 1000w, /assets/photos/general-bonifacio-1600.webp 1600w, /assets/photos/general-bonifacio-2000.webp 2000w",
    "width": 1600,
    "height": 1200,
    "category": "buggy",
    "alt": {
      "fr": "Un Polaris General orange et noir avec deux visiteurs devant la mer et les falaises de Bonifacio",
      "en": "An orange and black Polaris General with two visitors overlooking the sea and Bonifacio’s cliffs",
      "it": "Un Polaris General arancione e nero con due visitatori davanti al mare e alle falesie di Bonifacio"
    }
  },
  {
    "id": "quad-coucher-soleil",
    "src": "/assets/photos/quad-coucher-soleil-1600.webp",
    "srcset": "/assets/photos/quad-coucher-soleil-640.webp 640w, /assets/photos/quad-coucher-soleil-1000.webp 1000w, /assets/photos/quad-coucher-soleil-1600.webp 1600w, /assets/photos/quad-coucher-soleil-2000.webp 2000w",
    "width": 1600,
    "height": 801,
    "category": "quad",
    "alt": {
      "fr": "Un quad gris avec deux casques devant la baie au coucher du soleil",
      "en": "A grey quad with two helmets overlooking the bay at sunset",
      "it": "Un quad grigio con due caschi davanti alla baia al tramonto"
    }
  },
  {
    "id": "social-convoi-soleil",
    "src": "/assets/photos/social-convoi-soleil-1024.webp",
    "srcset": "/assets/photos/social-convoi-soleil-640.webp 640w, /assets/photos/social-convoi-soleil-1000.webp 1000w, /assets/photos/social-convoi-soleil-1024.webp 1024w",
    "width": 1024,
    "height": 768,
    "category": "buggy",
    "alt": {
      "fr": "Un convoi de buggys entre les rochers et le maquis sous un soleil orange",
      "en": "A buggy convoy among rocks and scrubland under an orange sun",
      "it": "Un convoglio di buggy tra le rocce e la macchia sotto un sole arancione"
    }
  },
  {
    "id": "social-rzr-soleil",
    "src": "/assets/photos/social-rzr-soleil-864.webp",
    "srcset": "/assets/photos/social-rzr-soleil-640.webp 640w, /assets/photos/social-rzr-soleil-864.webp 864w",
    "width": 864,
    "height": 1080,
    "category": "buggy",
    "alt": {
      "fr": "Un buggy Polaris RZR bleu et noir sous un ciel flamboyant au coucher du soleil",
      "en": "A blue and black Polaris RZR buggy under a fiery sunset sky",
      "it": "Un buggy Polaris RZR blu e nero sotto un cielo infuocato al tramonto"
    }
  },
  {
    "id": "social-rzr-phares",
    "src": "/assets/photos/social-rzr-phares-864.webp",
    "srcset": "/assets/photos/social-rzr-phares-640.webp 640w, /assets/photos/social-rzr-phares-864.webp 864w",
    "width": 864,
    "height": 1080,
    "category": "buggy",
    "alt": {
      "fr": "Un buggy aux phares allumés sur une piste rocheuse devant la mer",
      "en": "A buggy with its headlights on along a rocky trail overlooking the sea",
      "it": "Un buggy con i fari accesi su una pista rocciosa davanti al mare"
    }
  },
  {
    "id": "social-buggy-belvedere",
    "src": "/assets/photos/social-buggy-belvedere-1152.webp",
    "srcset": "/assets/photos/social-buggy-belvedere-640.webp 640w, /assets/photos/social-buggy-belvedere-1000.webp 1000w, /assets/photos/social-buggy-belvedere-1152.webp 1152w",
    "width": 1152,
    "height": 2048,
    "category": "buggy",
    "alt": {
      "fr": "Un buggy arrêté sur un belvédère au soleil couchant avec une chèvre au premier plan",
      "en": "A buggy parked at a viewpoint at sunset with a goat in the foreground",
      "it": "Un buggy fermo su un belvedere al tramonto con una capra in primo piano"
    }
  },
  {
    "id": "social-convoi-crepuscule",
    "src": "/assets/photos/social-convoi-crepuscule-1080.webp",
    "srcset": "/assets/photos/social-convoi-crepuscule-640.webp 640w, /assets/photos/social-convoi-crepuscule-1000.webp 1000w, /assets/photos/social-convoi-crepuscule-1080.webp 1080w",
    "width": 1080,
    "height": 1350,
    "category": "buggy",
    "alt": {
      "fr": "Un convoi de buggys sur une piste étroite du maquis face au ciel rose du soir",
      "en": "A buggy convoy on a narrow scrubland trail facing a pink evening sky",
      "it": "Un convoglio di buggy su una stretta pista nella macchia davanti al cielo rosa della sera"
    }
  },
  {
    "id": "social-bergerie-soleil",
    "src": "/assets/photos/social-bergerie-soleil-1080.webp",
    "srcset": "/assets/photos/social-bergerie-soleil-640.webp 640w, /assets/photos/social-bergerie-soleil-1000.webp 1000w, /assets/photos/social-bergerie-soleil-1080.webp 1080w",
    "width": 1080,
    "height": 1350,
    "category": "corse",
    "alt": {
      "fr": "La cheminée en pierre de la bergerie dans la lumière dorée du soir",
      "en": "The sheepfold’s stone chimney in the golden evening light",
      "it": "Il camino in pietra della bergerie nella luce dorata della sera"
    }
  },
  {
    "id": "social-panorama-soleil",
    "src": "/assets/photos/social-panorama-soleil-1440.webp",
    "srcset": "/assets/photos/social-panorama-soleil-640.webp 640w, /assets/photos/social-panorama-soleil-1000.webp 1000w, /assets/photos/social-panorama-soleil-1440.webp 1440w",
    "width": 1440,
    "height": 1800,
    "category": "corse",
    "alt": {
      "fr": "Le soleil orange descend sur la mer au-delà des collines et du maquis",
      "en": "The orange sun sets over the sea beyond the hills and scrubland",
      "it": "Il sole arancione tramonta sul mare oltre le colline e la macchia"
    }
  },
  {
    "id": "social-buggy-bleu-orange",
    "src": "/assets/photos/social-buggy-bleu-orange-1080.webp",
    "srcset": "/assets/photos/social-buggy-bleu-orange-640.webp 640w, /assets/photos/social-buggy-bleu-orange-1000.webp 1000w, /assets/photos/social-buggy-bleu-orange-1080.webp 1080w",
    "width": 1080,
    "height": 1350,
    "category": "buggy",
    "alt": {
      "fr": "Un buggy bleu et l’avant d’un buggy orange sous le ciel du soir",
      "en": "A blue buggy beside the front of an orange buggy under an evening sky",
      "it": "Un buggy blu accanto alla parte anteriore di un buggy arancione sotto il cielo della sera"
    }
  },
  {
    "id": "social-quad-rouge",
    "src": "/assets/photos/social-quad-rouge-1440.webp",
    "srcset": "/assets/photos/social-quad-rouge-640.webp 640w, /assets/photos/social-quad-rouge-1000.webp 1000w, /assets/photos/social-quad-rouge-1440.webp 1440w",
    "width": 1440,
    "height": 1800,
    "category": "quad",
    "alt": {
      "fr": "Un quad rouge à deux places à la base de départ de Corsica Ranger",
      "en": "A red two-seat quad at Corsica Ranger’s departure base",
      "it": "Un quad rosso a due posti alla base di partenza di Corsica Ranger"
    }
  },
  {
    "id": "social-general-soleil",
    "src": "/assets/photos/social-general-soleil-1080.webp",
    "srcset": "/assets/photos/social-general-soleil-640.webp 640w, /assets/photos/social-general-soleil-1000.webp 1000w, /assets/photos/social-general-soleil-1080.webp 1080w",
    "width": 1080,
    "height": 1350,
    "category": "buggy",
    "alt": {
      "fr": "Un Polaris General orange et noir sur une piste au coucher du soleil",
      "en": "An orange and black Polaris General on a trail at sunset",
      "it": "Un Polaris General arancione e nero su una pista al tramonto"
    }
  },
  {
    "id": "social-quad-crique",
    "src": "/assets/photos/social-quad-crique-1152.webp",
    "srcset": "/assets/photos/social-quad-crique-640.webp 640w, /assets/photos/social-quad-crique-1000.webp 1000w, /assets/photos/social-quad-crique-1152.webp 1152w",
    "width": 1152,
    "height": 2048,
    "category": "quad",
    "alt": {
      "fr": "Un quad au bord d’une crique rocheuse et de la mer bleue",
      "en": "A quad beside a rocky cove and the blue sea",
      "it": "Un quad accanto a una cala rocciosa e al mare blu"
    }
  },
  {
    "id": "social-base-oliviers",
    "src": "/assets/photos/social-base-oliviers-1440.webp",
    "srcset": "/assets/photos/social-base-oliviers-640.webp 640w, /assets/photos/social-base-oliviers-1000.webp 1000w, /assets/photos/social-base-oliviers-1440.webp 1440w",
    "width": 1440,
    "height": 1800,
    "category": "quad",
    "alt": {
      "fr": "Des quads à la base de départ à l’ombre des oliviers",
      "en": "Quads at the departure base in the shade of olive trees",
      "it": "Quad alla base di partenza all’ombra degli ulivi"
    }
  },
  {
    "id": "social-flotte-quads",
    "src": "/assets/photos/social-flotte-quads-1440.webp",
    "srcset": "/assets/photos/social-flotte-quads-640.webp 640w, /assets/photos/social-flotte-quads-1000.webp 1000w, /assets/photos/social-flotte-quads-1440.webp 1440w",
    "width": 1440,
    "height": 1800,
    "category": "quad",
    "alt": {
      "fr": "Des quads noirs et gris alignés à la base Corsica Ranger",
      "en": "Black and grey quads lined up at the Corsica Ranger base",
      "it": "Quad neri e grigi allineati alla base Corsica Ranger"
    }
  }
];

export const villaPhotos = {
  "lavezzi": [
    {
      "id": "lavezzi-1",
      "src": "/assets/photos/lavezzi-1-1024.webp",
      "srcset": "/assets/photos/lavezzi-1-640.webp 640w, /assets/photos/lavezzi-1-1000.webp 1000w, /assets/photos/lavezzi-1-1024.webp 1024w",
      "width": 1024,
      "height": 768,
      "category": "maisons",
      "alt": {
        "fr": "La piscine privée et le spa de la Villa Lavezzi parmi les pierres et les arbres",
        "en": "Villa Lavezzi’s private pool and spa among stones and trees",
        "it": "La piscina privata e la spa di Villa Lavezzi tra pietre e alberi"
      }
    },
    {
      "id": "lavezzi-2",
      "src": "/assets/photos/lavezzi-2-1024.webp",
      "srcset": "/assets/photos/lavezzi-2-640.webp 640w, /assets/photos/lavezzi-2-1000.webp 1000w, /assets/photos/lavezzi-2-1024.webp 1024w",
      "width": 1024,
      "height": 768,
      "category": "maisons",
      "alt": {
        "fr": "La piscine et le spa de la Villa Lavezzi vus depuis la terrasse",
        "en": "Villa Lavezzi’s pool and spa seen from the terrace",
        "it": "La piscina e la spa di Villa Lavezzi viste dalla terrazza"
      }
    },
    {
      "id": "lavezzi-3",
      "src": "/assets/photos/lavezzi-3-1024.webp",
      "srcset": "/assets/photos/lavezzi-3-640.webp 640w, /assets/photos/lavezzi-3-1000.webp 1000w, /assets/photos/lavezzi-3-1024.webp 1024w",
      "width": 1024,
      "height": 768,
      "category": "maisons",
      "alt": {
        "fr": "Le séjour lumineux et la table ronde de la Villa Lavezzi",
        "en": "Villa Lavezzi’s bright living room and round dining table",
        "it": "Il soggiorno luminoso e il tavolo rotondo di Villa Lavezzi"
      }
    },
    {
      "id": "lavezzi-4",
      "src": "/assets/photos/lavezzi-4-1024.webp",
      "srcset": "/assets/photos/lavezzi-4-640.webp 640w, /assets/photos/lavezzi-4-1000.webp 1000w, /assets/photos/lavezzi-4-1024.webp 1024w",
      "width": 1024,
      "height": 768,
      "category": "maisons",
      "alt": {
        "fr": "Une chambre à deux lits de la Villa Lavezzi avec placard miroir",
        "en": "A twin bedroom at Villa Lavezzi with a mirrored wardrobe",
        "it": "Una camera con due letti di Villa Lavezzi e armadio a specchio"
      }
    },
    {
      "id": "lavezzi-5",
      "src": "/assets/photos/lavezzi-5-1024.webp",
      "srcset": "/assets/photos/lavezzi-5-640.webp 640w, /assets/photos/lavezzi-5-1000.webp 1000w, /assets/photos/lavezzi-5-1024.webp 1024w",
      "width": 1024,
      "height": 768,
      "category": "maisons",
      "alt": {
        "fr": "Une chambre double aux tons jaunes à la Villa Lavezzi",
        "en": "A yellow-toned double bedroom at Villa Lavezzi",
        "it": "Una camera matrimoniale dai toni gialli di Villa Lavezzi"
      }
    },
    {
      "id": "lavezzi-6",
      "src": "/assets/photos/lavezzi-6-1024.webp",
      "srcset": "/assets/photos/lavezzi-6-640.webp 640w, /assets/photos/lavezzi-6-1000.webp 1000w, /assets/photos/lavezzi-6-1024.webp 1024w",
      "width": 1024,
      "height": 768,
      "category": "maisons",
      "alt": {
        "fr": "Une chambre double aux tons clairs à la Villa Lavezzi",
        "en": "A light-toned double bedroom at Villa Lavezzi",
        "it": "Una camera matrimoniale dai toni chiari di Villa Lavezzi"
      }
    }
  ],
  "cavallo": [
    {
      "id": "cavallo-1",
      "src": "/assets/photos/cavallo-1-953.webp",
      "srcset": "/assets/photos/cavallo-1-640.webp 640w, /assets/photos/cavallo-1-953.webp 953w",
      "width": 953,
      "height": 768,
      "category": "maisons",
      "alt": {
        "fr": "La façade en pierre et la piscine privée de la Villa Cavallo",
        "en": "Villa Cavallo’s stone façade and private swimming pool",
        "it": "La facciata in pietra e la piscina privata di Villa Cavallo"
      }
    },
    {
      "id": "cavallo-2",
      "src": "/assets/photos/cavallo-2-1024.webp",
      "srcset": "/assets/photos/cavallo-2-640.webp 640w, /assets/photos/cavallo-2-1000.webp 1000w, /assets/photos/cavallo-2-1024.webp 1024w",
      "width": 1024,
      "height": 768,
      "category": "maisons",
      "alt": {
        "fr": "La Villa Cavallo en pierre et son jardin arboré",
        "en": "The stone-built Villa Cavallo and its leafy garden",
        "it": "Villa Cavallo in pietra e il suo giardino alberato"
      }
    },
    {
      "id": "cavallo-3",
      "src": "/assets/photos/cavallo-3-1024.webp",
      "srcset": "/assets/photos/cavallo-3-640.webp 640w, /assets/photos/cavallo-3-1000.webp 1000w, /assets/photos/cavallo-3-1024.webp 1024w",
      "width": 1024,
      "height": 769,
      "category": "maisons",
      "alt": {
        "fr": "La salle à manger ouverte sur le séjour de la Villa Cavallo",
        "en": "Villa Cavallo’s dining room opening onto the living room",
        "it": "La sala da pranzo aperta sul soggiorno di Villa Cavallo"
      }
    },
    {
      "id": "cavallo-4",
      "src": "/assets/photos/cavallo-4-1024.webp",
      "srcset": "/assets/photos/cavallo-4-640.webp 640w, /assets/photos/cavallo-4-1000.webp 1000w, /assets/photos/cavallo-4-1024.webp 1024w",
      "width": 1024,
      "height": 768,
      "category": "maisons",
      "alt": {
        "fr": "Une chambre double au mur rouge à la Villa Cavallo",
        "en": "A double bedroom with a red wall at Villa Cavallo",
        "it": "Una camera matrimoniale con parete rossa di Villa Cavallo"
      }
    },
    {
      "id": "cavallo-5",
      "src": "/assets/photos/cavallo-5-1024.webp",
      "srcset": "/assets/photos/cavallo-5-640.webp 640w, /assets/photos/cavallo-5-1000.webp 1000w, /assets/photos/cavallo-5-1024.webp 1024w",
      "width": 1024,
      "height": 768,
      "category": "maisons",
      "alt": {
        "fr": "La terrasse couverte de la Villa Cavallo avec vue sur le maquis",
        "en": "Villa Cavallo’s covered terrace overlooking the scrubland",
        "it": "La terrazza coperta di Villa Cavallo con vista sulla macchia"
      }
    },
    {
      "id": "cavallo-6",
      "src": "/assets/photos/cavallo-6-1024.webp",
      "srcset": "/assets/photos/cavallo-6-640.webp 640w, /assets/photos/cavallo-6-1000.webp 1000w, /assets/photos/cavallo-6-1024.webp 1024w",
      "width": 1024,
      "height": 768,
      "category": "maisons",
      "alt": {
        "fr": "Une chambre double aux tons gris à la Villa Cavallo",
        "en": "A grey-toned double bedroom at Villa Cavallo",
        "it": "Una camera matrimoniale dai toni grigi di Villa Cavallo"
      }
    }
  ]
};
